WITH STATION_ROW AS(
    SELECT ID,
    LAT_N,
    ROW_NUMBER() OVER(ORDER BY ID) AS INDEX_ID
    FROM STATION
)
SELECT ROUND(LAT_N,4)
 FROM STATION_ROW
 WHERE INDEX_ID = (SELECT COUNT(INDEX_ID)/2 FROM STATION_ROW);
